name: Deploy PR Preview

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

jobs:
  deploy-preview:
    name: Deploy PR Preview
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    environment:
      name: pr-preview-${{ github.event.number }}
      url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr-${{ github.event.number }}/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.7.6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build project for PR preview
        run: pnpm build
        env:
          NODE_ENV: production
          VITE_BASE_PATH: /sip-vibe-meme/pr-${{ github.event.number }}/

      - name: Setup preview directory
        run: |
          mkdir -p preview/pr-${{ github.event.number }}
          cp -r dist/* preview/pr-${{ github.event.number }}/
          
          # Create or update index.html for PR list
          cat > preview/index.html << EOF
          <!DOCTYPE html>
          <html>
          <head>
            <title>PR Previews - Sip Vibe Meme</title>
            <style>
              body { font-family: system-ui, sans-serif; margin: 40px; }
              .pr-link { 
                display: block; 
                padding: 12px; 
                margin: 8px 0; 
                background: #f5f5f5; 
                border-radius: 8px; 
                text-decoration: none; 
                color: #333;
              }
              .pr-link:hover { background: #e5e5e5; }
            </style>
          </head>
          <body>
            <h1>🔥 Sip Vibe Meme - PR Previews</h1>
            <p>Available PR previews:</p>
            <a href="pr-${{ github.event.number }}/" class="pr-link">
              PR #${{ github.event.number }}: ${{ github.event.pull_request.title }}
            </a>
            <p><a href="../">← Back to main site</a></p>
          </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages (PR Preview)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./preview
          destination_dir: .
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy PR #${{ github.event.number }} preview'

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const previewUrl = `https://${context.repo.owner}.github.io/${context.repo.repo}/pr-${prNumber}/`;
            
            // Find existing preview comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });
            
            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('🚀 Preview deployed')
            );
            
            const body = `🚀 **Preview deployed!**
            
            ✅ Your changes are now live at: ${previewUrl}
            
            📱 Test your changes on different devices and screen sizes.
            
            ---
            
            *This preview will be updated automatically when you push new commits to this PR.*`;
            
            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: body,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: body,
              });
            }

  cleanup-preview:
    name: Cleanup PR Preview
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove PR preview directory
        run: |
          if [ -d "pr-${{ github.event.number }}" ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git rm -rf "pr-${{ github.event.number }}"
            git commit -m "Clean up PR #${{ github.event.number }} preview" || exit 0
            git push
          fi

      - name: Comment cleanup on PR
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `🧹 **Preview cleaned up**
              
              The preview for this PR has been removed since the PR was closed.`,
            });
